# Railway Configuration for Quest Platform Backend

[build]
builder = "NIXPACKS"
watchPatterns = ["backend/**"]

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
